### ISSUE TITLE
Error - mode 1280x720x60 not supported

### ISSUE THREAD

**Issue by mangoppola** [XITRIX/Moonlight-Switch#145]
Whenever I try to launch sunshine on my switch, I get the error in the title. The problem started after updating sunshine to version 0.22.0.
This happens with two different consoles, with the latest (to date) version of moonlight, which is 1.0.0; other devices (my phone) connect with no problems.
I tried changing resolution, framerate and codec; I also tried disabling hardware acceleration.
The desired resolutions and framerates are all present in the advertised list.
The consoles will connect to older versions of sunshine (I tried 0.20.0) just fine.

Here's some info about the systems I am using
Switch:
- Moonlight version: 1.0.0
- Base firmware: 16.1.0
- Atmosphere version: 1.6.2

Desktop:
- OS: Manjaro Linux, kernel 6.7.7
- DE: KDE plasma 5.27.10
- GPU: EVGA 1070Ti, nvidia proprietary driver
- Sunshine 0.22.0, downloaded from AUR (sunshine-bin)

**Comment by XITRIX** [comment]
It’s the bug of sunshine, add any random resolution in the end of the list in Sunshine’s resolutions config, it should solve your issue

**Comment by mangoppola** [comment]
Thank you! This solved the issue. I added '1x1' to sunshine's list of advertised resolutions and now it's working fine.

**Comment by xconwayx** [comment]
I am having the same issue after updating today. I attempted to add 1x1 to the Advertised Resolutions Area and 1920x1200 as I noticed in another forum post that this resolved the issue. Unfortunately for me, this is still an issue.

**Comment by XITRIX** [comment]
Try to play around with list of resolutions, it should fix this issue somehow, also try to check nightly build of Sunshine, looks like they fixed it (not checked by myself)

**Comment by xconwayx** [comment]
> Try to play around with list of resolutions, it should fix this issue somehow, also try to check nightly build of Sunshine, looks like they fixed it (not checked by myself)

I just found out about the nightly builds. This seems to resolve the issue. Thank you.

**Comment by wolfyzz22** [comment]
can one of u help me i cant find the list of reslouutions and i need hlep asap

**Comment by giuseppericco** [comment]
> can one of u help me i cant find the list of reslouutions and i need hlep asap

It's not hard at all: on your host machine, access the web configuration page (http://localhost:47990 by default, I believe), insert your credentials and navigate to the "Video" section. There, you will find a list of resolution. Just add the one you need there

**Comment by MauritsMolberg** [comment]
Is dd_manual_resolution the one you mean? Because that's the only resolution related value I can change from the Audio/Video settings, after enabling "Use manual resolution", and it does not fix the issue for me.  My Sunshine version is v2025.122.141614.

**Comment by giuseppericco** [comment]
It seems like advertised resolutions are not displayed in the web interface anymore. In Linux, a list of advertised resolutions can be found under `~/.config/sunshine/sunshine.conf`; `1x1` is in fact at the bottom of this list for me.
Note however that the original issue is almost a year old now and was related to an old version of sunshine (not moonlight). For me, removing `1x1` from the list of advertised resolutions had no effect whatsoever and my switch was still able to connect to my pc just fine, so I'd wager your issue lies somewhere else
